services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: ITSolutionsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: