# Generated by Django 5.1.1 on 2024-09-16 02:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цвет автомобиля',
                'verbose_name_plural': 'Цвета автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна автомобиля',
                'verbose_name_plural': 'Страны автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Введите название валюты', max_length=128, verbose_name='Тип валюты')),
                ('value', models.DecimalField(decimal_places=2, help_text='Введите значение валюты', max_digits=10, verbose_name='Значение валюты')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='KppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид КПП автомобиля',
                'verbose_name_plural': 'Виды КПП автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Kuzov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кузов автомобиля',
                'verbose_name_plural': 'Кузова автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Privod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид привода автомобиля',
                'verbose_name_plural': 'Виды приводов автомобилей',
            },
        ),
        migrations.CreateModel(
            name='UniqueCarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уникальный цвет автомобиля',
                'verbose_name_plural': 'Уникальные цвета автомобилей',
            },
        ),
        migrations.CreateModel(
            name='UniqueCarKpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уникальный КПП автомобиля',
                'verbose_name_plural': 'Уникальные КПП автомобилей',
            },
        ),
        migrations.CreateModel(
            name='UniqueCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
                ('mark_name', models.CharField(help_text='Введите марку модели автомобиля', max_length=256, verbose_name='Марка модели автомобиля')),
            ],
            options={
                'verbose_name': 'Уникальная модель автомобиля',
                'verbose_name_plural': 'Уникальные модели автомобилей',
            },
        ),
        migrations.CreateModel(
            name='UniqueCarPrivod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уникальный привод автомобиля',
                'verbose_name_plural': 'Уникальные приводы автомобилей',
            },
        ),
        migrations.CreateModel(
            name='UniqueCarPw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уникальная мощность автомобиля',
                'verbose_name_plural': 'Уникальные мощности автомобилей',
            },
        ),
        migrations.CreateModel(
            name='UniqueMarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уникальная марка автомобиля',
                'verbose_name_plural': 'Уникальные марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_date', models.DateField(help_text='Выберите дату проведения аукциона', verbose_name='Дата аукциона')),
                ('auction', models.CharField(help_text='Введите название аукциона', max_length=1024, verbose_name='Название аукциона')),
                ('year', models.IntegerField(help_text='Введите год автомобиля', verbose_name='Год автомобиля')),
                ('eng_v', models.IntegerField()),
                ('pw', models.CharField(blank=True, max_length=256, null=True)),
                ('grade', models.CharField(blank=True, max_length=1024, null=True)),
                ('mileage', models.IntegerField(help_text='Введите пробег автомобиля', verbose_name='Пробег')),
                ('equip', models.CharField(max_length=256)),
                ('rate', models.CharField(max_length=10)),
                ('finish', models.IntegerField()),
                ('expenses_rus', models.IntegerField(blank=True, help_text='Введите число расходов в России', null=True, verbose_name='Расходы в России')),
                ('expenses_jpn', models.IntegerField(blank=True, help_text='Введите число расходов по стране экспортера', null=True, verbose_name='Расходы по стране экспортера')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления записи')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), help_text='Введите ссылки на изображения автомобиля через запятую', size=3, verbose_name='Фотографии')),
                ('true_priv', models.CharField(max_length=512)),
                ('true_color', models.CharField(max_length=512)),
                ('true_kpp', models.CharField(max_length=512)),
                ('age', models.IntegerField(help_text='Введите возраст автомобиля', verbose_name='Возраст автомобиля')),
                ('is_sunction', models.BooleanField()),
                ('color_id', models.ForeignKey(blank=True, help_text='Выберите цвет автомобиля', null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.color', verbose_name='Цвет автомобиля')),
                ('country_id', models.ForeignKey(help_text='Выберите страну производителя автомобиля', on_delete=django.db.models.deletion.CASCADE, to='cars.country', verbose_name='Страна автомобиля')),
                ('kpp_type', models.ForeignKey(help_text='Выберите тип КПП', on_delete=django.db.models.deletion.CASCADE, to='cars.kpptype', verbose_name='КПП автомобиля')),
                ('kuzov_id', models.ForeignKey(help_text='Выберите кузов автомобиля', on_delete=django.db.models.deletion.CASCADE, to='cars.kuzov', verbose_name='Кузов автомобиля')),
                ('mark_id', models.ForeignKey(help_text='Выберите марку автомобиля', on_delete=django.db.models.deletion.CASCADE, to='cars.mark', verbose_name='Марка автомобиля')),
                ('model_id', models.ForeignKey(help_text='Выберите модель автомобиля', on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель автомобиля')),
                ('priv_id', models.ForeignKey(blank=True, help_text='Выберите тип привода автомобиля', null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.privod', verbose_name='Привод автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
