# Generated by Django 5.1.1 on 2024-09-13 01:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquemarkmodel',
            name='models',
        ),
        migrations.AddField(
            model_name='uniquemarkmodel',
            name='cars',
            field=models.ManyToManyField(related_name='unique_marks', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='country_id',
            field=models.ForeignKey(help_text='Выберите страну производителя автомобиля', on_delete=django.db.models.deletion.CASCADE, to='cars.country', verbose_name='Страна автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), help_text='Введите ссылки на изображения автомобиля через запятую', size=3, verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='kpptype',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='kuzov',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='privod',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='uniquemarkmodel',
            name='mark',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
