# Generated by Django 5.1.1 on 2024-09-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='auction',
            field=models.CharField(max_length=1024, verbose_name='Название аукциона'),
        ),
        migrations.AlterField(
            model_name='car',
            name='eng_v',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='equip',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='car',
            name='finish',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='grade',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pw',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='car',
            name='true_color',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='car',
            name='true_priv',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год автомобиля'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название цвета автомобиля'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название страны автомобиля'),
        ),
        migrations.AlterField(
            model_name='kpptype',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название КПП автомобиля'),
        ),
        migrations.AlterField(
            model_name='kuzov',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название кузова автомобиля'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название марки автомобиля'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название модели автомобиля'),
        ),
        migrations.AlterField(
            model_name='privod',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название привода автомобиля'),
        ),
    ]
