# Generated by Django 5.1.1 on 2024-09-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_uniquemarkmodel_models_uniquemarkmodel_cars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquemarkmodel',
            options={'verbose_name': 'Список машин по марке автомобиля', 'verbose_name_plural': 'Списки мошин по маркам автомобилям'},
        ),
        migrations.RemoveField(
            model_name='uniquemarkmodel',
            name='cars',
        ),
        migrations.AddField(
            model_name='uniquemarkmodel',
            name='cars',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
