# Generated by Django 5.1.1 on 2024-09-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_uniquemarkmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название параметра', max_length=256, verbose_name='Название параметра')),
                ('cars', models.TextField(help_text='Введите список машин', verbose_name='Список машин')),
            ],
            options={
                'verbose_name': 'Список машин по цвету',
                'verbose_name_plural': 'Списки машин по цветам',
            },
        ),
        migrations.AlterModelOptions(
            name='uniquemarkmodel',
            options={'verbose_name': 'Список машин по марке', 'verbose_name_plural': 'Списки машин по маркам'},
        ),
        migrations.RemoveField(
            model_name='uniquemarkmodel',
            name='mark',
        ),
        migrations.AddField(
            model_name='uniquemarkmodel',
            name='name',
            field=models.CharField(default=0, help_text='Введите название параметра', max_length=256, verbose_name='Название параметра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uniquemarkmodel',
            name='cars',
            field=models.TextField(help_text='Введите список машин', verbose_name='Список машин'),
        ),
    ]
