# Generated by Django 5.1.1 on 2024-09-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Введите ссылку на канал', verbose_name='Сслыка на канал')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название видео', max_length=512, verbose_name='Название видео')),
                ('description', models.TextField(help_text='Введите описание видео', verbose_name='Описание видео')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название плей-листа', max_length=256, verbose_name='Название плей-листа')),
                ('count', models.IntegerField(help_text='Введите количество видео', verbose_name='Количество видео')),
                ('chanel', models.ForeignKey(help_text='Введите канал', on_delete=django.db.models.deletion.CASCADE, to='youtube.chanel', verbose_name='Канал')),
            ],
        ),
    ]
