# Generated by Django 5.1.1 on 2024-09-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chanel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Плей-лист', 'verbose_name_plural': 'Плей-листы'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='count',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(default=0, help_text='Введите ID плейлиста', max_length=255, verbose_name='ID плейлиста'),
            preserve_default=False,
        ),
    ]
