# Generated by Django 5.1.1 on 2024-09-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=0, help_text='Введите ID видео', max_length=255, verbose_name='ID видео'),
            preserve_default=False,
        ),
    ]
