# Generated by Django 5.1.1 on 2024-09-17 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_chanel_options_alter_playlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(default=0, help_text='Укажите плей-лист', on_delete=django.db.models.deletion.CASCADE, to='youtube.playlist', verbose_name='Плей-лист'),
            preserve_default=False,
        ),
    ]
