# Generated by Django 5.1.1 on 2024-09-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url_shorts',
            field=models.URLField(blank=True, help_text='Ссылка на скачивание видео Shorts', max_length=512, null=True, verbose_name='Ссылка на скачивание Shorts'),
        ),
    ]
