# Generated by Django 5.1.1 on 2024-09-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_video_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(help_text='Выберите видео', related_name='playlists', to='youtube.video', verbose_name='Видео'),
        ),
    ]
