# Generated by Django 5.1.1 on 2024-09-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_video_url_shorts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelplaylist',
            options={'verbose_name': 'Связь Канал->Плей-лист', 'verbose_name_plural': 'Связи Каналы->Плей-листы'},
        ),
    ]
