# Generated by Django 5.1.1 on 2024-09-20 04:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название компании', max_length=256, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_review', models.FloatField(verbose_name='Средняя оценка')),
                ('count_review', models.IntegerField(verbose_name='Количество отзывов')),
                ('reviews', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None, verbose_name='Отзывы')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_company.company', verbose_name='Компания')),
            ],
        ),
    ]
