# Generated by Django 5.1.1 on 2024-09-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avg_review',
            field=models.CharField(max_length=10, verbose_name='Средняя оценка'),
        ),
    ]
